language: node_js

node_js:
    - "7"
    - "6"
    - "4"

script:
    - npm test

after_success: npm run coverage

cache:
    yarn: true
    directories:
        - node_modules

notifications:
  email: falses
